# Jekyll config. Reference:
# https://github.com/mojombo/jekyll/wiki/Configuration

# But GitHub overrides some configs, including disabling plugins!
# So we develop with those same configs:
# http://help.github.com/pages/#using_jekyll_for_complex_layouts

safe: true
source: .
destination: ./_site

mini_magick:
  photos:
    source: ./img/originals/photos/
    destination: ./img/photos/
    resize: "1600x1600"

  paintings:
    source: ./img/originals/paintings
    destination: ./img/paintings/
    resize: "1600x1600^"
    
  photos_thumb:
    source: ./img/originals/photos/
    destination: ./img/photos/thumb/
    resize: "800x600^"
    gravity: "Center"
    crop: "800x600+0+0"    

  paintings_thumb:
    source: ./img/originals/paintings
    destination: ./img/paintings/thumb/
    resize: "800x600^"
    gravity: "Center"
    crop: "800x600+0+0"
